language: python
  python:
    - "3.6"
  install:
    - pip install coverage python-coveralls
  script:
    - coverage run ./test_cupp.py
  after_success:
    - coverage report
    - coveralls
Â© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
